version: 0.0
os: windows
files:
  - source: /
    destination: C:\Users\Administrator\Desktop\web
hooks:

  BeforeInstall:
    - location: /appstop.bat
      timeout: 180
      runas: administrator
  AfterInstall:
    - location: /appstart.bat
      timeout: 180
      runas: administrator
